import JSZip from 'jszip'
import { saveAs } from 'file-saver'
import type { LessonConfig, AssetFile } from '../types/lesson'

// Main function to generate a complete lesson package
export async function generateLessonPackage(config: LessonConfig, assets: AssetFile[]): Promise<Blob> {
  const zip = new JSZip()
  
  // Add all assets to the zip
  const assetsFolder = zip.folder('assets')
  if (assetsFolder) {
    for (const asset of assets) {
      assetsFolder.file(asset.name, asset.file)
    }
  }
  
  // Generate template files based on the original generator structure
  await generateTemplateFiles(zip, config)
  
  // Generate the zip file
  return await zip.generateAsync({ type: 'blob' })
}

async function generateTemplateFiles(zip: JSZip, config: LessonConfig) {
  // Generate index.htm (main lesson page)
  zip.file('index.htm', generateIndexHTML(config))
  
  // Generate pageTemplate.php
  zip.file('pageTemplate.php', generatePageTemplate(config))
  
  // Generate download.php
  zip.file('download.php', generateDownloadPHP(config))
  
  // Generate print.php
  zip.file('print.php', generatePrintPHP(config))
  
  // Generate navigation menu
  zip.file('navmenu.inc.php', generateNavMenu(config))
  
  // Generate CSS files
  const cssFolder = zip.folder('css')
  if (cssFolder) {
    cssFolder.file('module-custom.css', generateCustomCSS(config))
  }
  
  // Generate content pages
  await generateContentPages(zip, config)
  
  // Add optional pages
  if (config.includeQuiz) {
    zip.file('quiz.htm', generateQuizPage(config))
  }
  
  if (config.includePreassessment) {
    zip.file('preassessment.htm', generatePreassessmentPage(config))
  }
  
  if (config.includeSurvey) {
    zip.file('survey.htm', generateSurveyPage(config))
  }
  
  if (config.includeResources) {
    zip.file('resources.htm', generateResourcesPage(config))
  }
  
  if (config.includeContributors) {
    zip.file('contributors.htm', generateContributorsPage(config))
  }
  
  // Copy static assets based on template type
  await copyStaticAssets(zip, config)
}

function generateIndexHTML(config: LessonConfig): string {
  const pageNavigation = config.pages.length > 0 ? `
                <div class="lesson-navigation">
                    <h3>Lesson Contents</h3>
                    <ul class="lesson-menu">
                        ${config.pages.map((page, index) => `
                        <li><a href="page${index + 1}.htm">${page.title}</a></li>
                        `).join('')}
                    </ul>
                </div>
                ` : ''

  const bootstrapCSS = config.useBootstrap ? '<link href="css/bootstrap.min.css" rel="stylesheet">' : ''
  const bootstrapJS = config.useBootstrap ? '<script src="js/bootstrap.min.js"></script>' : ''
  const orgSection = config.organizationName ? `<p><strong>Organization:</strong> ${config.organizationName}</p>` : ''

  return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${config.lessonTitle}</title>
    ${bootstrapCSS}
    <link href="css/module-custom.css" rel="stylesheet">
</head>
<body>
    <div class="container">
        <header>
            <h1>${config.lessonTitle}</h1>
            <p class="lead">${config.shortDescription}</p>
        </header>
        
        <?php include 'navmenu.inc.php'; ?>
        
        <main>
            <div class="lesson-content">
                <h2>Welcome to ${config.lessonTitle}</h2>
                <p>${config.longDescription}</p>
                
                <div class="lesson-info">
                    <p><strong>Author:</strong> ${config.authorName}</p>
                    ${orgSection}
                    <p><strong>Publication:</strong> ${config.pubMonth} ${config.pubYear}</p>
                    <p><strong>Version:</strong> ${config.version}</p>
                </div>
                ${pageNavigation}
            </div>
        </main>
        
        <footer>
            <p>&copy; ${config.pubYear} ${config.organizationName || config.authorName}. All rights reserved.</p>
        </footer>
    </div>
    
    ${bootstrapJS}
</body>
</html>`
}

function generatePageTemplate(config: LessonConfig): string {
  const bootstrapCSS = config.useBootstrap ? '<link href="css/bootstrap.min.css" rel="stylesheet">' : ''
  const bootstrapJS = config.useBootstrap ? '<script src="js/bootstrap.min.js"></script>' : ''

  return `<?php
// Page template for ${config.lessonTitle}
// Generated by MetEd Lesson Generator

class LessonPage {
    private $title;
    private $content;
    private $pageNumber;
    private $totalPages;
    
    public function __construct($title, $content, $pageNumber, $totalPages) {
        $this->title = $title;
        $this->content = $content;
        $this->pageNumber = $pageNumber;
        $this->totalPages = $totalPages;
    }
    
    public function render() {
        $lessonTitle = "${config.lessonTitle}";
        $authorName = "${config.authorName}";
        $organizationName = "${config.organizationName}";
        
        echo $this->getHeader();
        echo $this->getNavigation();
        echo $this->getContent();
        echo $this->getFooter();
    }
    
    private function getHeader() {
        return '
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>' . $this->title . ' - ${config.lessonTitle}</title>
    ${bootstrapCSS}
    <link href="css/module-custom.css" rel="stylesheet">
</head>
<body>
    <div class="container">
        <header>
            <h1>${config.lessonTitle}</h1>
            <nav class="breadcrumb">
                <a href="index.htm">Home</a> &raquo; ' . $this->title . '
            </nav>
        </header>
        ';
    }
    
    private function getNavigation() {
        $nav = '<nav class="lesson-nav">';
        if ($this->pageNumber > 1) {
            $prevPage = $this->pageNumber - 1;
            $nav .= '<a href="page' . $prevPage . '.htm" class="nav-prev">&laquo; Previous</a>';
        }
        
        $nav .= '<span class="nav-info">Page ' . $this->pageNumber . ' of ' . $this->totalPages . '</span>';
        
        if ($this->pageNumber < $this->totalPages) {
            $nextPage = $this->pageNumber + 1;
            $nav .= '<a href="page' . $nextPage . '.htm" class="nav-next">Next &raquo;</a>';
        }
        
        $nav .= '</nav>';
        return $nav;
    }
    
    private function getContent() {
        return '
        <main>
            <h2>' . htmlspecialchars($this->title) . '</h2>
            <div class="lesson-content">
                ' . $this->content . '
            </div>
        </main>
        ';
    }
    
    private function getFooter() {
        return '
        <footer>
            <p>&copy; ${config.pubYear} ${config.organizationName || config.authorName}. All rights reserved.</p>
        </footer>
    </div>
    
    ${bootstrapJS}
</body>
</html>
        ';
    }
}
?>`
}

function generateDownloadPHP(config: LessonConfig): string {
  const filename = config.lessonAcronym || 'lesson'
  
  return `<?php
// Download handler for ${config.lessonTitle}
// Generated by MetEd Lesson Generator

// Set headers for file download
header('Content-Type: application/octet-stream');
header('Content-Disposition: attachment; filename="${filename}-materials.zip"');
header('Content-Transfer-Encoding: binary');

// Basic download functionality
if (isset($_GET['file'])) {
    $file = basename($_GET['file']);
    $filePath = 'assets/' . $file;
    
    if (file_exists($filePath) && is_file($filePath)) {
        readfile($filePath);
        exit;
    } else {
        http_response_code(404);
        echo 'File not found.';
        exit;
    }
} else {
    http_response_code(400);
    echo 'No file specified.';
    exit;
}
?>`
}

function generatePrintPHP(config: LessonConfig): string {
  const pageBreaks = config.pages.map((page) => `
        <div class="page-break">
            <h2>${page.title}</h2>
            <div>
                ${page.content}
            </div>
        </div>
        `).join('')

  return `<?php
// Print version for ${config.lessonTitle}
// Generated by MetEd Lesson Generator

$lessonTitle = "${config.lessonTitle}";
$authorName = "${config.authorName}";
$organizationName = "${config.organizationName}";
$pubDate = "${config.pubMonth} ${config.pubYear}";
$version = "${config.version}";
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo $lessonTitle; ?> - Print Version</title>
    <link href="css/module-print.css" rel="stylesheet" media="print">
    <style>
        body { font-family: Arial, sans-serif; }
        .print-header { text-align: center; border-bottom: 2px solid #333; padding-bottom: 20px; }
        .lesson-content { margin: 20px 0; }
        .page-break { page-break-before: always; }
        @media print {
            .no-print { display: none; }
        }
    </style>
</head>
<body>
    <div class="print-header">
        <h1><?php echo $lessonTitle; ?></h1>
        <p>Author: <?php echo $authorName; ?></p>
        <?php if ($organizationName): ?>
        <p>Organization: <?php echo $organizationName; ?></p>
        <?php endif; ?>
        <p>Published: <?php echo $pubDate; ?> | Version: <?php echo $version; ?></p>
    </div>
    
    <div class="lesson-content">
        <p>${config.longDescription}</p>
        ${pageBreaks}
    </div>
    
    <script class="no-print">
        window.onload = function() {
            window.print();
        }
    </script>
</body>
</html>`
}

function generateNavMenu(config: LessonConfig): string {
  const pageLinks = config.pages.map((page, index) => `
        <li><a href="page${index + 1}.htm">${page.title}</a></li>
        `).join('')

  const optionalLinks = [
    config.includeQuiz ? '<li><a href="quiz.htm">Quiz</a></li>' : '',
    config.includePreassessment ? '<li><a href="preassessment.htm">Pre-assessment</a></li>' : '',
    config.includeSurvey ? '<li><a href="survey.htm">Survey</a></li>' : '',
    config.includeResources ? '<li><a href="resources.htm">Resources</a></li>' : '',
    config.includeContributors ? '<li><a href="contributors.htm">Contributors</a></li>' : ''
  ].filter(Boolean).join('')

  return `<?php
// Navigation menu for ${config.lessonTitle}
?>
<nav class="lesson-navigation">
    <ul class="nav-menu">
        <li><a href="index.htm">Home</a></li>
        ${pageLinks}
        ${optionalLinks}
        <li><a href="print.php" target="_blank">Print Version</a></li>
    </ul>
</nav>`
}

function generateCustomCSS(config: LessonConfig): string {
  const customStyles = config.customCSS || ''
  
  return `/* Custom CSS for ${config.lessonTitle} */
/* Generated by MetEd Lesson Generator */

body {
    font-family: 'Arial', sans-serif;
    line-height: 1.6;
    color: #333;
    background-color: #f8f9fa;
}

.container {
    max-width: 1200px;
    margin: 0 auto;
    padding: 20px;
    background: white;
    box-shadow: 0 0 10px rgba(0,0,0,0.1);
}

header {
    text-align: center;
    margin-bottom: 30px;
    padding-bottom: 20px;
    border-bottom: 2px solid #007bff;
}

header h1 {
    color: #007bff;
    margin-bottom: 10px;
}

.lesson-navigation {
    background: #e9ecef;
    padding: 15px;
    border-radius: 5px;
    margin: 20px 0;
}

.nav-menu {
    list-style: none;
    padding: 0;
    margin: 0;
    display: flex;
    flex-wrap: wrap;
    gap: 10px;
}

.nav-menu li a {
    display: block;
    padding: 10px 15px;
    background: #007bff;
    color: white;
    text-decoration: none;
    border-radius: 3px;
    transition: background-color 0.3s;
}

.nav-menu li a:hover {
    background: #0056b3;
}

.lesson-content {
    margin: 30px 0;
    padding: 20px;
}

.lesson-info {
    background: #f8f9fa;
    padding: 15px;
    border-left: 4px solid #007bff;
    margin: 20px 0;
}

.lesson-nav {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 15px;
    background: #e9ecef;
    border-radius: 5px;
    margin: 20px 0;
}

.nav-prev, .nav-next {
    padding: 8px 15px;
    background: #007bff;
    color: white;
    text-decoration: none;
    border-radius: 3px;
}

.nav-prev:hover, .nav-next:hover {
    background: #0056b3;
}

.nav-info {
    font-weight: bold;
}

footer {
    text-align: center;
    margin-top: 40px;
    padding-top: 20px;
    border-top: 1px solid #dee2e6;
    color: #6c757d;
}

/* Responsive design */
@media (max-width: 768px) {
    .container {
        padding: 10px;
    }
    
    .nav-menu {
        flex-direction: column;
    }
    
    .lesson-nav {
        flex-direction: column;
        gap: 10px;
    }
}

${customStyles}`
}

async function generateContentPages(zip: JSZip, config: LessonConfig) {
  config.pages.forEach((page, index) => {
    const pageNumber = index + 1
    const fileName = `page${pageNumber}.htm`
    
    const prevLink = pageNumber > 1 ? `<a href="page${pageNumber - 1}.htm" class="nav-prev">&laquo; Previous</a>` : '<span></span>'
    const nextLink = pageNumber < config.pages.length ? `<a href="page${pageNumber + 1}.htm" class="nav-next">Next &raquo;</a>` : '<span></span>'
    
    const bootstrapCSS = config.useBootstrap ? '<link href="css/bootstrap.min.css" rel="stylesheet">' : ''
    const bootstrapJS = config.useBootstrap ? '<script src="js/bootstrap.min.js"></script>' : ''
    
    const pageContent = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${page.title} - ${config.lessonTitle}</title>
    ${bootstrapCSS}
    <link href="css/module-custom.css" rel="stylesheet">
</head>
<body>
    <div class="container">
        <header>
            <h1>${config.lessonTitle}</h1>
            <nav class="breadcrumb">
                <a href="index.htm">Home</a> &raquo; ${page.title}
            </nav>
        </header>
        
        <?php include 'navmenu.inc.php'; ?>
        
        <nav class="lesson-nav">
            ${prevLink}
            <span class="nav-info">Page ${pageNumber} of ${config.pages.length}</span>
            ${nextLink}
        </nav>
        
        <main>
            <h2>${page.title}</h2>
            <div class="lesson-content">
                ${page.content}
            </div>
        </main>
        
        <footer>
            <p>&copy; ${config.pubYear} ${config.organizationName || config.authorName}. All rights reserved.</p>
        </footer>
    </div>
    
    ${bootstrapJS}
</body>
</html>`
    
    zip.file(fileName, pageContent)
  })
}

function generateQuizPage(config: LessonConfig): string {
  return generateSpecialPage(config, 'Quiz', `
    <div class="quiz-container">
        <p>This is a placeholder for the quiz content. You can customize this section with your assessment questions.</p>
        <div class="quiz-question">
            <h3>Sample Question</h3>
            <p>What is the main topic of this lesson?</p>
            <div class="quiz-options">
                <label><input type="radio" name="q1" value="a"> Option A</label><br>
                <label><input type="radio" name="q1" value="b"> Option B</label><br>
                <label><input type="radio" name="q1" value="c"> Option C</label><br>
                <label><input type="radio" name="q1" value="d"> Option D</label>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Submit Quiz</button>
    </div>
  `)
}

function generatePreassessmentPage(config: LessonConfig): string {
  return generateSpecialPage(config, 'Pre-assessment', `
    <div class="preassessment-container">
        <p>Please complete this pre-assessment to help us understand your current knowledge level.</p>
        <div class="assessment-question">
            <h3>Knowledge Check</h3>
            <p>Rate your familiarity with the topic:</p>
            <div class="rating-scale">
                <label><input type="radio" name="familiarity" value="1"> Very Low</label><br>
                <label><input type="radio" name="familiarity" value="2"> Low</label><br>
                <label><input type="radio" name="familiarity" value="3"> Medium</label><br>
                <label><input type="radio" name="familiarity" value="4"> High</label><br>
                <label><input type="radio" name="familiarity" value="5"> Very High</label>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Submit Assessment</button>
    </div>
  `)
}

function generateSurveyPage(config: LessonConfig): string {
  return generateSpecialPage(config, 'Survey', `
    <div class="survey-container">
        <p>Please provide your feedback about this lesson.</p>
        <div class="survey-question">
            <h3>Overall Rating</h3>
            <p>How would you rate this lesson overall?</p>
            <select name="rating" class="form-control">
                <option value="">Please select...</option>
                <option value="5">Excellent</option>
                <option value="4">Good</option>
                <option value="3">Fair</option>
                <option value="2">Poor</option>
                <option value="1">Very Poor</option>
            </select>
        </div>
        <div class="survey-question">
            <h3>Comments</h3>
            <textarea name="comments" rows="4" class="form-control" placeholder="Please share any additional feedback..."></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Submit Survey</button>
    </div>
  `)
}

function generateResourcesPage(config: LessonConfig): string {
  return generateSpecialPage(config, 'Resources', `
    <div class="resources-container">
        <p>Additional resources and materials for this lesson.</p>
        <div class="resource-section">
            <h3>Downloads</h3>
            <ul class="resource-list">
                <li><a href="download.php?file=lesson-materials.pdf">Lesson Materials (PDF)</a></li>
                <li><a href="download.php?file=references.pdf">Reference Documents</a></li>
            </ul>
        </div>
        <div class="resource-section">
            <h3>External Links</h3>
            <ul class="resource-list">
                <li><a href="#" target="_blank">Related Website 1</a></li>
                <li><a href="#" target="_blank">Related Website 2</a></li>
            </ul>
        </div>
    </div>
  `)
}

function generateContributorsPage(config: LessonConfig): string {
  const emailSection = config.authorEmail ? `<p>Email: <a href="mailto:${config.authorEmail}">${config.authorEmail}</a></p>` : ''
  const orgSection = config.organizationName ? `<p>Organization: ${config.organizationName}</p>` : ''

  return generateSpecialPage(config, 'Contributors', `
    <div class="contributors-container">
        <div class="contributor">
            <h3>Primary Author</h3>
            <p><strong>${config.authorName}</strong></p>
            ${emailSection}
            ${orgSection}
        </div>
        <div class="contributor">
            <h3>Acknowledgments</h3>
            <p>We would like to thank all contributors who made this lesson possible.</p>
        </div>
    </div>
  `)
}

function generateSpecialPage(config: LessonConfig, title: string, content: string): string {
  const bootstrapCSS = config.useBootstrap ? '<link href="css/bootstrap.min.css" rel="stylesheet">' : ''
  const bootstrapJS = config.useBootstrap ? '<script src="js/bootstrap.min.js"></script>' : ''

  return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${title} - ${config.lessonTitle}</title>
    ${bootstrapCSS}
    <link href="css/module-custom.css" rel="stylesheet">
</head>
<body>
    <div class="container">
        <header>
            <h1>${config.lessonTitle}</h1>
            <nav class="breadcrumb">
                <a href="index.htm">Home</a> &raquo; ${title}
            </nav>
        </header>
        
        <?php include 'navmenu.inc.php'; ?>
        
        <main>
            <h2>${title}</h2>
            <div class="lesson-content">
                ${content}
            </div>
        </main>
        
        <footer>
            <p>&copy; ${config.pubYear} ${config.organizationName || config.authorName}. All rights reserved.</p>
        </footer>
    </div>
    
    ${bootstrapJS}
</body>
</html>`
}

async function copyStaticAssets(zip: JSZip, config: LessonConfig) {
  // Add basic CSS structure
  const cssFolder = zip.folder('css')
  if (cssFolder && config.useBootstrap) {
    // Add a note about Bootstrap - in production, you'd copy the actual files
    cssFolder.file('bootstrap.min.css', '/* Bootstrap CSS should be added here */')
  }
  
  // Add basic JS structure
  if (config.useBootstrap) {
    const jsFolder = zip.folder('js')
    if (jsFolder) {
      jsFolder.file('bootstrap.min.js', '/* Bootstrap JS should be added here */')
    }
  }
  
  // Add README
  zip.file('README.md', generateReadme(config))
}

function generateReadme(config: LessonConfig): string {
  const features = [
    config.includeQuiz ? '- Quiz/Assessment page' : '',
    config.includePreassessment ? '- Pre-assessment page' : '',
    config.includeSurvey ? '- Survey/Feedback page' : '',
    config.includeResources ? '- Resources page' : '',
    config.includeContributors ? '- Contributors page' : '',
    '- Print-friendly version',
    '- Responsive design',
    config.useBootstrap ? '- Bootstrap CSS framework' : ''
  ].filter(Boolean).join('\n')

  return `# ${config.lessonTitle}

**Author:** ${config.authorName}  
**Organization:** ${config.organizationName}  
**Version:** ${config.version}  
**Published:** ${config.pubMonth} ${config.pubYear}  

## Description

${config.longDescription}

## Installation

1. Upload all files to your Apache web server
2. Ensure PHP is enabled on your server
3. Set appropriate permissions for file access
4. Access the lesson through index.htm

## File Structure

- \`index.htm\` - Main lesson homepage
- \`page*.htm\` - Individual lesson pages
- \`pageTemplate.php\` - PHP template for dynamic content
- \`download.php\` - File download handler
- \`print.php\` - Print-friendly version
- \`navmenu.inc.php\` - Navigation menu include
- \`css/\` - Stylesheets and custom CSS
- \`assets/\` - Images, videos, and other media files

## Features

${features}

## Generated by MetEd Lesson Generator

This lesson package was created using the MetEd Lesson Generator web application, which replaces the original Yeoman generator with a modern React-based interface.
`
}

// Export function to download generated package
export async function downloadLessonPackage(config: LessonConfig, assets: AssetFile[]) {
  try {
    const blob = await generateLessonPackage(config, assets)
    const filename = `${config.lessonAcronym || 'lesson'}-package.zip`
    saveAs(blob, filename)
  } catch (error) {
    console.error('Error generating lesson package:', error)
    throw new Error('Failed to generate lesson package')
  }
}